import React, { useState } from 'react';
import { AppState, QuizConfig, QuizResultRecord } from '../types';
import { CLASSES, NCERT_DATA } from '../constants';
import { 
  Sparkles, 
  BookOpen, 
  ArrowRight, 
  Zap, 
  BrainCircuit, 
  CheckCircle2, 
  ChevronDown, 
  Layers, 
  Award, 
  Flame, 
  Compass,
  BookMarked,
  Trophy,
  MessageSquare
} from 'lucide-react';

interface HomeViewProps {
  onStartQuizConfig: (config: QuizConfig) => void;
  onNavigate: (view: AppState) => void;
  recentHistory: QuizResultRecord[];
}

interface QuickPreset {
  title: string;
  className: string;
  subjectName: string;
  topics: string[];
  strength: 'Easy' | 'Medium' | 'Hard';
  quantity: number;
  badge: string;
  color: string;
}

export const HomeView: React.FC<HomeViewProps> = ({
  onStartQuizConfig,
  onNavigate,
  recentHistory,
}) => {
  const [activeFaq, setActiveFaq] = useState<number | null>(null);
  const [selectedDivision, setSelectedDivision] = useState<string>('All');

  const syllabusData = NCERT_DATA;

  const quickPresets: QuickPreset[] = [
    {
      title: 'Class 6 Science: Curiosity',
      className: 'Class 6',
      subjectName: 'Science (Curiosity)',
      topics: ['Chapter 1: The Wonderful World of Science', 'Chapter 2: Diversity in the Living World', 'Chapter 3: Mindful Eating: A Path to a Healthy Body'],
      strength: 'Medium',
      quantity: 10,
      badge: 'NCERT Curiosity',
      color: 'from-emerald-500/20 to-teal-500/20 border-emerald-500/30 text-emerald-400',
    },
    {
      title: 'Class 6 Maths: Ganita Prakash',
      className: 'Class 6',
      subjectName: 'Maths (Ganita Prakash)',
      topics: ['Chapter 1: Patterns in Mathematics', 'Chapter 2: Lines and Angles', 'Chapter 3: Number Play'],
      strength: 'Medium',
      quantity: 10,
      badge: 'Ganita Prakash',
      color: 'from-blue-500/20 to-cyan-500/20 border-cyan-500/30 text-cyan-400',
    },
    {
      title: 'Class 10 Board Sprint: Science',
      className: 'Class 10',
      subjectName: 'Science',
      topics: ['1: Chemical Reactions and Equations', '5: Life Processes', '9: Light – Reflection and Refraction', '11: Electricity'],
      strength: 'Medium',
      quantity: 10,
      badge: 'High Yield',
      color: 'from-amber-500/20 to-orange-500/20 border-amber-500/30 text-amber-400',
    },
    {
      title: 'Class 12 Physics: Electrostatics & Currents',
      className: 'Class 12',
      subjectName: 'Physics',
      topics: ['Electric Charges and Fields', 'Current Electricity', 'Moving Charges and Magnetism'],
      strength: 'Hard',
      quantity: 10,
      badge: 'Advanced',
      color: 'from-purple-500/20 to-pink-500/20 border-purple-500/30 text-purple-400',
    },
    {
      title: 'Class 9 Maths: Polynomials & Coordinate Geometry',
      className: 'Class 9',
      subjectName: 'Maths',
      topics: ['2: Polynomials', '3: Coordinate Geometry', '6: Lines and Angles', '7: Triangles'],
      strength: 'Medium',
      quantity: 10,
      badge: 'Core Concept',
      color: 'from-emerald-500/20 to-lime-500/20 border-emerald-500/30 text-emerald-400',
    },
    {
      title: 'Class 11 Chemistry: Structure of Atom & Thermodynamics',
      className: 'Class 11',
      subjectName: 'Chemistry',
      topics: ['Structure of Atom', 'Chemical Bonding and Molecular Structure', 'Chemical Thermodynamics'],
      strength: 'Hard',
      quantity: 10,
      badge: 'Analytical',
      color: 'from-rose-500/20 to-red-500/20 border-rose-500/30 text-rose-400',
    }
  ];

  const faqs = [
    {
      q: 'Is the assessment engine strictly aligned to official NCERT textbooks?',
      a: 'Yes. U Quiz is configured with official NCERT curricula from Class 1 through Class 12. Questions are dynamically generated by Gemini 2.5 Flash according to exact textbook chapters, terminology, and cognitive standards.'
    },
    {
      q: 'How does mathematical and scientific formula rendering work?',
      a: 'The assessment engine formats all mathematical notations, fractions, equations, powers, and scientific symbols with clean typographic precision, rendering formulas smoothly on any screen size.'
    },
    {
      q: 'Can I choose specific chapters or combine multiple topics?',
      a: 'Absolutely. The Custom Quiz Configurator allows you to select your target grade and subject, and pick any combination of chapters or topics you want to test.'
    },
    {
      q: 'What do the cognitive demand levels (Easy, Medium, Hard) mean?',
      a: 'Easy emphasizes direct factual recall and definitions; Medium evaluates conceptual understanding and direct applications; Hard generates multi-step analytical and problem-solving questions.'
    }
  ];

  // Group classes by divisions
  const divisions = [
    { id: 'All', label: 'All Classes (1-12)' },
    { id: 'Primary', label: 'Primary (1-5)', classes: ['Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5'] },
    { id: 'Middle', label: 'Middle (6-8)', classes: ['Class 6', 'Class 7', 'Class 8'] },
    { id: 'Secondary', label: 'Secondary (9-10)', classes: ['Class 9', 'Class 10'] },
    { id: 'Senior', label: 'Sr. Secondary (11-12)', classes: ['Class 11', 'Class 12'] },
  ];

  const filteredClasses = CLASSES.filter(cls => {
    if (selectedDivision === 'All') return true;
    const divObj = divisions.find(d => d.id === selectedDivision);
    return divObj?.classes?.includes(cls);
  });

  // Calculate overall stats from recent history
  const totalQuizzesTaken = recentHistory.length;
  const totalScore = recentHistory.reduce((acc, curr) => acc + curr.score, 0);
  const totalQuestions = recentHistory.reduce((acc, curr) => acc + curr.total, 0);
  const avgAccuracy = totalQuestions > 0 ? Math.round((totalScore / totalQuestions) * 100) : 0;

  return (
    <div className="space-y-16 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      
      {/* Hero Section */}
      <section className="relative rounded-3xl overflow-hidden border border-slate-800 bg-gradient-to-b from-slate-900/90 via-slate-900/60 to-slate-950 p-8 sm:p-12 lg:p-16 shadow-2xl">
        <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 rounded-full bg-emerald-500/10 blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-80 h-80 rounded-full bg-cyan-500/10 blur-3xl pointer-events-none" />
        
        <div className="relative z-10 max-w-3xl space-y-6">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold tracking-wide uppercase font-mono">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Aligned with Official NCERT Syllabus</span>
          </div>

          <h1 className="text-3xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight font-display text-white leading-[1.1]">
            Master every concept in the <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 via-teal-300 to-cyan-400">NCERT Syllabus</span>
          </h1>

          <p className="text-slate-300 text-base sm:text-lg leading-relaxed">
            Generate customized, topic-specific assessments with detailed NCERT-grounded explanations, high-precision mathematical typesetting, and official textbook curricula.
          </p>

          <div className="flex flex-wrap items-center gap-4 pt-2">
            <button
              onClick={() => onNavigate(AppState.SETUP)}
              className="flex items-center gap-2.5 px-6 py-3.5 rounded-xl bg-gradient-to-r from-emerald-400 to-lime-400 text-slate-950 font-bold text-base shadow-xl shadow-emerald-500/25 hover:shadow-emerald-500/40 hover:scale-[1.02] active:scale-[0.98] transition-all group cursor-pointer"
            >
              <span>Build Custom Quiz</span>
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </button>

            <button
              onClick={() => onNavigate(AppState.LEADERBOARD)}
              className="flex items-center gap-2.5 px-6 py-3.5 rounded-xl bg-amber-500/10 hover:bg-amber-500/20 border border-amber-500/30 text-amber-300 font-semibold text-base transition-all cursor-pointer"
            >
              <Trophy className="w-5 h-5 text-amber-400" />
              <span>Top 10 Leaderboard</span>
            </button>

            <button
              id="hero-chat-btn"
              onClick={() => onNavigate(AppState.CHAT)}
              className="flex items-center gap-2.5 px-6 py-3.5 rounded-xl bg-purple-500/15 hover:bg-purple-500/25 border border-purple-500/30 text-purple-300 font-semibold text-base transition-all cursor-pointer shadow-lg shadow-purple-500/10"
            >
              <MessageSquare className="w-5 h-5 text-purple-400" />
              <span>Study Chat & AI Tutor</span>
            </button>

            <button
              onClick={() => onNavigate(AppState.CURRICULUM)}
              className="flex items-center gap-2.5 px-6 py-3.5 rounded-xl bg-slate-800/80 hover:bg-slate-700/80 border border-slate-700 text-white font-semibold text-base transition-all cursor-pointer"
            >
              <BookOpen className="w-5 h-5 text-emerald-400" />
              <span>NCERT Curriculum</span>
            </button>
          </div>

          {/* Value Badges */}
          <div className="pt-4 flex flex-wrap gap-6 text-xs text-slate-400 font-medium">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Classes 1 to 12</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Official NCERT Textbooks</span>
            </div>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Step-by-Step Concept Rationales</span>
            </div>
          </div>
        </div>
      </section>

      {/* Syllabus Spotlight Card */}
      <section className="rounded-2xl border border-emerald-500/30 bg-gradient-to-r from-emerald-950/40 via-slate-900/80 to-slate-900/80 p-6 sm:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6 shadow-xl">
        <div className="space-y-2 max-w-2xl">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold font-mono bg-emerald-500/20 border border-emerald-500/40 text-emerald-300">
              OFFICIAL CURRICULUM
            </span>
            <span className="text-xs text-emerald-400 font-mono">Classes 1 to 12</span>
          </div>
          <h3 className="text-xl sm:text-2xl font-bold font-display text-white">
            Comprehensive NCERT Textbooks & Chapters
          </h3>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
            Practice questions mapped to official textbooks: <em>Curiosity</em> (Science), <em>Ganita Prakash</em> (Maths), <em>Exploring Society</em> (Social Science), <em>Poorvi</em> & <em>Malhar</em> (Languages), <em>Mridang</em> & <em>Maths Mela</em> (Primary), and Senior Secondary disciplines.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3 shrink-0">
          <button
            onClick={() => onNavigate(AppState.CURRICULUM)}
            className="flex items-center gap-2 px-5 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs shadow-md shadow-emerald-500/20 transition-all cursor-pointer"
          >
            <BookMarked className="w-4 h-4" />
            <span>Explore Full Syllabus</span>
          </button>
        </div>
      </section>

      {/* User Stats / Performance Summary (if any recent history exists) */}
      {totalQuizzesTaken > 0 && (
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
                <Award className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-lg font-bold font-display text-white">Your Assessment Progress</h3>
                <p className="text-xs text-slate-400">Performance across recent NCERT practice sessions</p>
              </div>
            </div>
            <button
              onClick={() => onNavigate(AppState.HISTORY)}
              className="text-xs font-semibold text-emerald-400 hover:text-emerald-300 flex items-center gap-1.5 transition-colors self-start sm:self-auto cursor-pointer"
            >
              <span>View Full History ({recentHistory.length})</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="bg-slate-950/60 p-4 rounded-xl border border-slate-800/80">
              <span className="text-xs text-slate-400 font-medium">Quizzes Completed</span>
              <p className="text-2xl font-bold font-display text-white mt-1">{totalQuizzesTaken}</p>
            </div>
            <div className="bg-slate-950/60 p-4 rounded-xl border border-slate-800/80">
              <span className="text-xs text-slate-400 font-medium">Overall Accuracy</span>
              <p className="text-2xl font-bold font-display text-emerald-400 mt-1">{avgAccuracy}%</p>
            </div>
            <div className="bg-slate-950/60 p-4 rounded-xl border border-slate-800/80">
              <span className="text-xs text-slate-400 font-medium">Questions Answered</span>
              <p className="text-2xl font-bold font-display text-white mt-1">{totalQuestions}</p>
            </div>
            <div className="bg-slate-950/60 p-4 rounded-xl border border-slate-800/80">
              <span className="text-xs text-slate-400 font-medium">Correct Responses</span>
              <p className="text-2xl font-bold font-display text-emerald-400 mt-1">{totalScore}</p>
            </div>
          </div>
        </section>
      )}

      {/* Quick Launch High-Yield Presets */}
      <section className="space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-2">
          <div>
            <div className="flex items-center gap-2 text-xs font-mono text-emerald-400 uppercase tracking-wider mb-1">
              <Zap className="w-3.5 h-3.5" />
              <span>Instant Start</span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-bold font-display text-white">
              Featured High-Yield NCERT Quizzes
            </h2>
          </div>
          <p className="text-sm text-slate-400">
            One-click curated practice sets from official NCERT curricula
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {quickPresets.map((preset, index) => (
            <div
              key={index}
              className="group relative rounded-2xl border border-slate-800/90 bg-slate-900/60 hover:bg-slate-900/90 hover:border-slate-700 p-6 flex flex-col justify-between transition-all duration-200 hover:-translate-y-1 hover:shadow-xl"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-bold font-mono border ${preset.color}`}>
                    {preset.badge}
                  </span>
                  <span className="text-xs font-medium text-slate-400 font-mono">
                    {preset.className} • {preset.quantity} Qs
                  </span>
                </div>

                <h3 className="text-lg font-bold font-display text-white group-hover:text-emerald-400 transition-colors leading-snug">
                  {preset.title}
                </h3>

                <p className="text-xs text-slate-400 line-clamp-2">
                  Topics: {preset.topics.join(', ')}
                </p>
              </div>

              <div className="pt-5 mt-4 border-t border-slate-800/60 flex items-center justify-between">
                <div className="flex items-center gap-1.5 text-xs text-slate-400">
                  <Flame className="w-3.5 h-3.5 text-amber-400" />
                  <span>{preset.strength} Difficulty</span>
                </div>

                <button
                  onClick={() => onStartQuizConfig({
                    class: preset.className,
                    subject: preset.subjectName,
                    topics: preset.topics,
                    strength: preset.strength,
                    quantity: preset.quantity,
                  })}
                  className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-emerald-500/10 hover:bg-emerald-500 border border-emerald-500/30 text-emerald-400 hover:text-slate-950 text-xs font-bold transition-all shadow-sm cursor-pointer"
                >
                  <span>Start Quiz</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Explore by Class / Grade Explorer */}
      <section className="space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-xs font-mono text-emerald-400 uppercase tracking-wider mb-1">
              <Compass className="w-3.5 h-3.5" />
              <span>Syllabus Matrix</span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-bold font-display text-white">
              Explore by Grade Level
            </h2>
          </div>

          {/* Division Filter Tabs */}
          <div className="flex flex-wrap items-center gap-1.5 bg-slate-900/80 p-1 rounded-xl border border-slate-800">
            {divisions.map(div => (
              <button
                key={div.id}
                onClick={() => setSelectedDivision(div.id)}
                className={`px-3 py-1 rounded-lg text-xs font-medium transition-all ${
                  selectedDivision === div.id
                    ? 'bg-emerald-500 text-slate-950 font-bold shadow-sm'
                    : 'text-slate-400 hover:text-white hover:bg-slate-800'
                }`}
              >
                {div.label}
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
          {filteredClasses.map((clsName) => {
            const classEntries = syllabusData.filter(d => d.className === clsName);
            const subjects = Array.from(new Set(classEntries.map(d => d.subjectName)));
            const chapterCount = classEntries.length;

            return (
              <div
                key={clsName}
                onClick={() => {
                  onNavigate(AppState.SETUP);
                }}
                className="group p-5 rounded-2xl border border-slate-800/80 bg-slate-900/40 hover:bg-slate-900/80 hover:border-emerald-500/40 transition-all cursor-pointer hover:-translate-y-0.5"
              >
                <div className="flex items-center justify-between mb-3">
                  <div className="w-9 h-9 rounded-xl bg-slate-800 flex items-center justify-center text-emerald-400 font-bold font-display text-sm group-hover:bg-emerald-500 group-hover:text-slate-950 transition-colors">
                    {clsName.replace('Class ', '')}
                  </div>
                  <span className="text-[11px] font-mono text-slate-400">
                    {chapterCount} Chapters
                  </span>
                </div>

                <h4 className="text-base font-bold font-display text-white group-hover:text-emerald-400 transition-colors">
                  {clsName}
                </h4>

                <div className="mt-2 flex flex-wrap gap-1">
                  {subjects.slice(0, 3).map((sub, i) => (
                    <span key={i} className="text-[10px] px-1.5 py-0.5 rounded bg-slate-800/80 text-slate-400">
                      {sub}
                    </span>
                  ))}
                  {subjects.length > 3 && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-slate-800/80 text-slate-400">
                      +{subjects.length - 3}
                    </span>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* Feature Pillars */}
      <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/40 space-y-3">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
            <BrainCircuit className="w-5 h-5" />
          </div>
          <h3 className="text-lg font-bold font-display text-white">Cognitive Depth Calibration</h3>
          <p className="text-sm text-slate-400 leading-relaxed">
            Customize question difficulty from foundational definitions (Easy) to multi-step analytical reasoning (Hard) with zero generic filler questions.
          </p>
        </div>

        <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/40 space-y-3">
          <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center text-cyan-400">
            <Layers className="w-5 h-5" />
          </div>
          <h3 className="text-lg font-bold font-display text-white">Mathematical & Scientific Precision</h3>
          <p className="text-sm text-slate-400 leading-relaxed">
            Equations, chemical reactions, radicals, and geometric notations are typeset natively with high-fidelity formula engine support.
          </p>
        </div>

        <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/40 space-y-3">
          <div className="w-10 h-10 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400">
            <BookOpen className="w-5 h-5" />
          </div>
          <h3 className="text-lg font-bold font-display text-white">Detailed NCERT Rationales</h3>
          <p className="text-sm text-slate-400 leading-relaxed">
            Every question comes with a comprehensive concept explanation directly referencing the NCERT principle, making every attempt an active learning session.
          </p>
        </div>
      </section>

      {/* FAQ Accordion */}
      <section className="rounded-2xl border border-slate-800 bg-slate-900/40 p-6 sm:p-8 space-y-6">
        <div>
          <h2 className="text-2xl font-bold font-display text-white">Frequently Asked Questions</h2>
          <p className="text-sm text-slate-400 mt-1">Everything you need to know about the U Quiz assessment system and syllabus updates</p>
        </div>

        <div className="divide-y divide-slate-800">
          {faqs.map((faq, idx) => {
            const isOpen = activeFaq === idx;
            return (
              <div key={idx} className="py-4">
                <button
                  onClick={() => setActiveFaq(isOpen ? null : idx)}
                  className="w-full flex items-center justify-between text-left group"
                >
                  <span className="text-base font-semibold text-slate-200 group-hover:text-emerald-400 transition-colors pr-4">
                    {faq.q}
                  </span>
                  <div className={`p-1.5 rounded-lg border border-slate-800 transition-transform ${isOpen ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400 rotate-180' : 'text-slate-400'}`}>
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <p className="mt-3 text-sm text-slate-400 leading-relaxed pr-8">
                    {faq.a}
                  </p>
                )}
              </div>
            );
          })}
        </div>
      </section>

    </div>
  );
};
